### 1. [簡答題] 請問 type(...) 跟 a.dtype 這兩個語法有什麼不同？

```
print('type(a): ', type(a))
print('a.dtype: ', a.dtype)
```

In [4]:
import numpy as np

In [7]:
a = np.random.randint(10, size=6) 
print('type(a): ', type(a))
print('a.dtype: ', a.dtype)

type(a):  <class 'numpy.ndarray'>
a.dtype:  int32


type代表這個物件的類別(例如現在a是陣列，因此type(a)就顯示為ndarray)  
a.type代表a這個陣列中的元素型態，因此顯示出的是int32


### 2. 請撰寫一個判斷 a 的元素是否等於指定資料型態的函式，並且通過測試。



In [35]:
def is_dtype(a, t):
    return (a.dtype == t)

In [36]:
a = np.random.randint(10, size=6) 

# 測試一
print(is_dtype(a, 'int')) # True

# 測試二
print(is_dtype(a, np.int)) # True

# 測試三
print(is_dtype(a, np.dtype('int'))) # True

True
True
True


### 3. [簡答題] 承上題，請判斷下列三種寫法為何不正確？

```
def is_dtype(a, t):
    return a.dtype is t

def is_dtype(a, t):
    return type(a) == np.dtype(t)

def is_dtype(a, t):
    return type(a) is np.dtype(t)
```

三個都不正確  
第一個用is來做判定，會需要所有規格都相同，因此前兩者的寫法在is的判定下無法達成  
第二、三個都是用type(a)，而type(a)回傳的是資料型態(陣列)，而非資料類型，因此也都不正確

# 延伸題

#1.將下列清單(list1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")


In [61]:
array1 = np.array(range(30))
print(array1)
array1.shape = (5,6)
print(array1)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


#2 呈上題的 array，找出被 6 除餘 1 的數的索引

In [66]:
print(np.where(array1 %6 ==1))
print(np.where(array1 %6 ==1,"Y", "N"))

(array([0, 1, 2, 3, 4], dtype=int64), array([1, 1, 1, 1, 1], dtype=int64))
[['N' 'Y' 'N' 'N' 'N' 'N']
 ['N' 'Y' 'N' 'N' 'N' 'N']
 ['N' 'Y' 'N' 'N' 'N' 'N']
 ['N' 'Y' 'N' 'N' 'N' 'N']
 ['N' 'Y' 'N' 'N' 'N' 'N']]


代表索引[0,1] [1,1] [2,1] [3,1] [4,1]皆滿足要求