# 基礎題

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


np.zeros會生成符合維度要求的0陣列  
np.empty生成出的陣列雖然同樣符合維度要求，但內部元素可能是不確定的(隨機生成)

### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [61]:
import numpy as np
a = np.random.rand(2, 3)
print(a)
print(np.rint(a))

[[0.41639375 0.94270961 0.01771428]
 [0.91808518 0.09313145 0.67818783]]
[[0. 1. 0.]
 [1. 0. 1.]]


以rint(a)來計算出a所有元素的四捨五入結果

### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [72]:
m = 20
n = 40
a = np.random.uniform(20, 40 , (2,3))
print(a)
print(np.rint(a))

[[23.84122505 21.53615981 22.97554919]
 [35.50418289 37.47035451 34.12785849]]
[[24. 22. 23.]
 [36. 37. 34.]]


利用random.uniform生成m~n之間的數字，再四捨五入得到結果

# 延伸題

**作業目標**<br>
在一個陣列中放入多屬性陣列，進一步對陣列做運算<br>
作業重點<br>
在建立結構化陣列前需要先設定屬性，在做運算時須注意資料屬性

題目:<br>
name_list = ['小明','小華','小菁','小美','小張','John','Mark','Tom']<br>
sex_list = ['boy','boy','girl','girl','boy','boy','boy','boy']<br>
weight_list = [67.5,75.3,50.1,45.5,80.8,90.4,78.4,70.7]<br>
rank_list = [8,1,5,4,7,6,2,3]<br>
myopia_list = [True,True,False,False,True,True,False,False]<br>
1. 將上列list依照['name', 'sex', 'weight', 'rank', 'myopia']順序擺入array，並且資料型態順序擺入[Unicode,Unicode,float,int,boolean]<br>
2. 呈上題，將array中體重(weight)數據集取出算出全部平均體重
3. 呈上題，進一步算出男生(sex欄位是boy)平均體重、女生(sex欄位是girl)平均體重


In [73]:
name_list = ['小明','小華','小菁','小美','小張','John','Mark','Tom']
sex_list = ['boy','boy','girl','girl','boy','boy','boy','boy']
weight_list = [67.5,75.3,50.1,45.5,80.8,90.4,78.4,70.7]
rank_list = [8,1,5,4,7,6,2,3]
myopia_list = [True,True,False,False,True,True,False,False]

In [125]:
#1. 將上列list依照['name', 'sex', 'weight', 'rank', 'myopia']順序擺入array，並且資料型態順序擺入[Unicode,Unicode,float,int,boolean]
dt = np.dtype({'names':('name', 'sex', 'weight', 'rank','myopia'), 'formats':((np.unicode_, 4), (np.unicode_, 4), float , int , bool)})
print(dt)
c = np.zeros(8,dtype=dt)
c['name'] = name_list
c['sex'] = sex_list
c['weight'] = weight_list
c['rank'] = rank_list
c['myopia'] = myopia_list
print(c)


[('name', '<U4'), ('sex', '<U4'), ('weight', '<f8'), ('rank', '<i4'), ('myopia', '?')]
[('小明', 'boy', 67.5, 8,  True) ('小華', 'boy', 75.3, 1,  True)
 ('小菁', 'girl', 50.1, 5, False) ('小美', 'girl', 45.5, 4, False)
 ('小張', 'boy', 80.8, 7,  True) ('John', 'boy', 90.4, 6,  True)
 ('Mark', 'boy', 78.4, 2, False) ('Tom', 'boy', 70.7, 3, False)]


In [120]:
#2. 呈上題，將array中體重(weight)數據集取出算出全部平均體重
np.mean(c['weight'])


69.8375

In [143]:
#3.  呈上題，進一步算出男生(sex欄位是boy)平均體重、女生(sex欄位是girl)平均體重
print(np.mean(c[np.where(c['sex'] == 'boy')]['weight']))
print(np.mean(c[np.where(c['sex'] == 'girl')]['weight']))

77.18333333333332
47.8
