# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [1]:
'''
list只能把數據的最外層轉換為list，因此會看到a轉化完之後的list裡面依然是三組一維的array
tolist則會把所有輸入都轉為list，因此最後形成的list裡面一樣是三組list
'''

'\nlist只能把數據的最外層轉換為list，因此會看到a轉化完之後的list裡面依然是三組一維的array\ntolist則會把所有輸入都轉為list，因此最後形成的list裡面一樣是三組list\n'

### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [4]:
# 記得先 Import 正確的套件

import numpy as np

In [11]:

a = np.random.randint(10, size=6) 

print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(len(a))
print(type(a))

[2 9 8 7 1 3]
1
(6,)
6
int32
4
6
<class 'numpy.ndarray'>


第一列是顯示a的內容，是一個一維的陣列  

第二列代表a的維度，因為是一維所以是1  

第三列是a每個維度的大小，因為是一維陣列，因此維度只寫6，後面空著  

第四列是a的元素數量，總共6個  

第五列是資料型態，這邊設定成int32  

第六列是每個元素的佔用空間，因為是int32，所以顯示出4。如果是int64，這邊就會顯示出8  

第七列是a的長度，我用len函數呼叫出來，a的長度是6  

第八列是a的資料型態，看到顯示結果為numpy.ndarray  



In [12]:
b = np.random.randint(10, size=(3,4)) 

print(b)
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)
print(len(b))
print(type(b))

[[2 9 4 4]
 [1 8 0 8]
 [6 0 8 0]]
2
(3, 4)
12
int32
4
3
<class 'numpy.ndarray'>


第一列是顯示b的內容，是一個二維的3x4陣列  

第二列代表b的維度，因為是二維所以是2  

第三列是b每個維度的大小，因為是二維的3x4陣列，因此這邊顯示(3,4)  

第四列是b的元素數量，總共12個  

第五列是資料型態，這邊設定成int32  

第六列是每個元素的佔用空間，因為是int32，所以顯示出4。如果是int64，這邊就會顯示出8  

第七列是b第一個維度的長度，因此顯示出3  

第八列是b的資料型態，看到顯示結果為numpy.ndarray  

In [18]:
c = np.random.randint(10, size=(2,3,2)) 

print(c)
print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)
print(c.itemsize)
print(len(c))
print(type(c))

[[[8 7]
  [4 6]
  [0 1]]

 [[6 6]
  [3 5]
  [4 1]]]
3
(2, 3, 2)
12
int32
4
2
<class 'numpy.ndarray'>


第一列是顯示c的內容，是一個三維的2x3x2陣列  

第二列代表c的維度，因為是三維所以是3  

第三列是c每個維度的大小，因為是三維的2x3x2陣列，因此這邊顯示(2, 3, 2)  

第四列是c的元素數量，總共12個  

第五列是資料型態，這邊設定成int32  

第六列是每個元素的佔用空間，因為是int32，所以顯示出4。如果是int64，這邊就會顯示出8  

第七列是c第一個維度的長度，因此顯示出2  

第八列是c的資料型態，看到顯示結果為numpy.ndarray  

### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [121]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[5, 2, 4, 2, 4, 2]
[5, 2, 4, 2, 4, 2]


因為a本身就是一維陣列，所以a.tolist與list(a)的效果相同

In [123]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


print([list(b[0]),list(b[1]),list(b[2])])

[[5, 7, 0, 9], [3, 2, 9, 8], [5, 0, 0, 3]]
[array([5, 7, 0, 9]), array([3, 2, 9, 8]), array([5, 0, 0, 3])]
[[5, 7, 0, 9], [3, 2, 9, 8], [5, 0, 0, 3]]


因為直接list(b)只會把b轉換成三層的array，因此我改成對b的每一層各自做list，這樣的結果就會與b.tolist()相同(最後一行)

In [124]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))

print([[list(c[0,0]),list(c[0,1]),list(c[0,2])],[list(c[1,0]),list(c[1,1]),list(c[1,2])]])

[[[4, 7], [7, 6], [2, 6]], [[7, 7], [9, 3], [4, 0]]]
[array([[4, 7],
       [7, 6],
       [2, 6]]), array([[7, 7],
       [9, 3],
       [4, 0]])]
[[[4, 7], [7, 6], [2, 6]], [[7, 7], [9, 3], [4, 0]]]


In [128]:
c.ndim

3

跟上小題相同，對c的每一層各自做list。由於c的每一層也是2維陣列，因此還要再重複一次相同的步驟，最後就得到與c.tolist()相同的結果

In [134]:
def tolist(iterable):    
    if iterable.ndim==3:
        z = []
        x = []
        goal = []
        for i in range(len(iterable)):
            for j in range(len(iterable[i])):
                for k in range(len(iterable[i][j])):
                    x.append(iterable[i][j][k])
                z.append(x)
                x = []
            goal.append(z)
            z=[]

        return(goal)
    elif iterable.ndim==2:
        x = []
        goal = []
        for i in range(len(iterable)):
            for j in range(len(iterable[i])):
                x.append(iterable[i][j])
        goal.append(x)
        x = []

        return(goal)    
    elif iterable.ndim==1:
        goal = list(iterable)
        return(goal)    

    

    
print(tolist(a))
print(tolist(b))
print(tolist(c))


[5, 2, 4, 2, 4, 2]
[5, 2, 4, 2, 4, 2]
[[5, 7, 0, 9], [3, 2, 9, 8], [5, 0, 0, 3]]
[[5, 7, 0, 9, 3, 2, 9, 8, 5, 0, 0, 3]]
[[[4, 7], [7, 6], [2, 6]], [[7, 7], [9, 3], [4, 0]]]
[[[4, 7], [7, 6], [2, 6]], [[7, 7], [9, 3], [4, 0]]]


In [ ]:
print(a.tolist())
print(b.tolist())
print(c.tolist())


[7, 6, 7, 3, 7, 5]
[[5, 7, 4, 6], [9, 4, 0, 1], [9, 1, 2, 9]]
[[[0, 4], [0, 1], [9, 5]], [[8, 7], [8, 2], [6, 0]]]


定義的tolist函數裡面加上先判斷array維度的if判斷句，接著與之前同樣重複貼上內容形成list，可以看到結果與tolist()是相同的  

但此函數只定義到維度3而已，雖然答案相同，但是如果要對應更高維的array則還要再加上判斷式

## 延伸題

#### 1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。


In [143]:
import numpy as np
e = np.arange(0,21,1)
print(e)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


#### 2.呈上題，將以上數列取出偶數。

In [148]:
e[e%2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

#### 3.呈1題，將數列取出3的倍數。

In [149]:
e[e%3==0]

array([ 0,  3,  6,  9, 12, 15, 18])